In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
df_2022 = pd.read_csv('./csv/version3/2022_final.csv')
df_2023 = pd.read_csv('./csv/version3/2023_final.csv')
df_2024 = pd.read_csv('./csv/version3/2024_final.csv')

In [31]:
df_2023

,id,name,kucbt_score,program,first_name,gender
0,KUCAT_2023_1,Shreeyut Thapa,1224,BE in Computer Engineering,shreeyut,m
1,KUCAT_2023_2,Kiyoshi Pandey,672,BE in Computer Engineering,kiyoshi,f
2,KUCAT_2023_3,Anmol Kumar Yadav,622,BE in Geomacs Engineering,anmol,m
3,KUCAT_2023_4,Shailesh Paudel,578,BE in Computer Engineering,shailesh,m
4,KUCAT_2023_5,Yubraj Panthi,674,BE in Civil Engineering (Specializaon in Hydro...,yubraj,m
...,...,...,...,...,...,...
2258,KUCAT_2023_3208,Sabin Shrees,578,BE in Civil Engineering (Specializaon in Hydro...,sabin,m
2259,KUCAT_2023_3210,Lajjita Bhaa,587,BArch in Architecture,lajjita,f
2260,KUCAT_2023_3211,Anup Khanal,731,BE in Computer Engineering,anup,m
2261,KUCAT_2023_3212,Prasoon Dahal,821,BE in Computer Engineering,prasoon,m
2262,KUCAT_2023_3214,Kelvin Sangroula,755,BE in Mechanical Engineering(Design and Manufa...,kelvin,m

In [9]:
df_2023['program'].value_counts()

program
BE in Computer Engineering                                     1248
BE in Civil Engineering (Specializaon in Hydropower)            456
BArch in Architecture                                           187
BTech in Arficial Intelligence                                   81
BE in Geomacs Engineering                                        75
BE in Electrical & Electronic Engineering (Power & Control)      49
BE in Mechanical Engineering(Design and Manufacturing)           43
BE in Mechanical Engineering(Automobile)                         41
BE in Electrical & Electronic Engineering (Communicaon)          37
BE in Mechanical Engineering(Energy Technology)                  16
BE in Mechanical Engineering(Hydropower)                         14
BE in Mining Engineering                                          8
BE in Chemical Engineering                                        8
Name: count, dtype: int64

In [10]:
df_2022['program'].value_counts()

program
BE in Computer Engineering                                     770
BE in Civil Engineering (Specialization in Hydropower)         437
BArch in Architecture                                          177
BE in Geomatics Engineering                                     68
BE in Mechanical Engineering(Automobile)                        42
BE in Mechanical Engineering(Design and Manufacturing)          41
BTech in Artificial Intelligence                                40
BE in Electrical & Electronic Engineering (Power & Control)     40
BE in Electrical & Electronic Engineering (Communication)       29
BE in Chemical Engineering                                      11
BE in Mechanical Engineering(Hydropower)                         5
BE in Mechanical Engineering(Energy Technology)                  5
Name: count, dtype: int64

In [11]:
df_2024['program'].value_counts()

program
BE in Computer Engineering                                     1080
BE in Civil Engineering (Specialization in Hydropower)          287
BArch in Architecture                                           161
BE in Geomatics Engineering                                      68
BTech in Artificial Intelligence                                 62
BE in Mechanical Engineering(Automobile)                         32
BE in Mechanical Engineering(Design and Manufacturing)           28
BE in Electrical & Electronic Engineering (Power & Control)      28
BE in Electrical & Electronic Engineering (Communication)        26
BE in Mechanical Engineering(Energy Technology)                   5
BE in Mechanical Engineering(Hydropower)                          4
BE in Mining Engineering                                          3
Name: count, dtype: int64

In [45]:
df_2023.loc[
    df_2023['program'] == 'BE in Civil Engineering (Specializaon in Hydropower)',
    'program'
] = 'BE in Civil Engineering (Specialization in Hydropower)'

In [47]:
df_2023.loc[df_2023['program'] == 'BTech in Arficial Intelligence', 'program'] = 'BTech in Artificial Intelligence'

In [48]:
df_2023.loc[
    df_2023['program'] == 'BE in Geomacs Engineering',
    'program'
] = 'BE in Geomatics Engineering'

In [49]:
df_2023.program.value_counts()

program
BE in Computer Engineering                                     1248
BE in Civil Engineering (Specialization in Hydropower)          456
BArch in Architecture                                           187
BTech in Artificial Intelligence                                 81
BE in Geomatics Engineering                                      75
BE in Electrical & Electronic Engineering (Power & Control)      49
BE in Mechanical Engineering(Design and Manufacturing)           43
BE in Mechanical Engineering(Automobile)                         41
BE in Electrical & Electronic Engineering (Communicaon)          37
BE in Mechanical Engineering(Energy Technology)                  16
BE in Mechanical Engineering(Hydropower)                         14
BE in Mining Engineering                                          8
BE in Chemical Engineering                                        8
Name: count, dtype: int64

In [58]:
dfs = [df_2022, df_2023, df_2024]
year = 2022
for df in dfs:
    df['year'] = f"{year}"
    year += 1
df = pd.concat(dfs, ignore_index = True)

In [60]:
df_2024

,id,name,kucbt_score,program,first_name,gender,year
0,KUSoE_2024_1,Aashutosh Singh,721,BE in Computer Engineering,aashutosh,m,2024
1,KUSoE_2024_2,PRANAY MALLIK,641,BE in Computer Engineering,pranay,m,2024
2,KUSoE_2024_3,SARJU SAHANI,709,BArch in Architecture,sarju,f,2024
3,KUSoE_2024_6,Ashmit Shah,721,BE in Electrical & Electronic Engineering (Com...,ashmit,m,2024
4,KUSoE_2024_7,Surasa Silpakar,873,BE in Computer Engineering,surasa,f,2024
...,...,...,...,...,...,...,...
1779,KUSoE_2024_2559,Bibek Pariyar,596,BE in Computer Engineering,bibek,m,2024
1780,KUSoE_2024_2561,Nabraj Sigdel,645,BE in Computer Engineering,nabraj,m,2024
1781,KUSoE_2024_2564,Simran Neupane,542,BE in Computer Engineering,simran,m,2024
1782,KUSoE_2024_2565,Swikar Kharal,760,BE in Computer Engineering,swikar,m,2024
1783,KUSoE_2024_2566,Kriti Tiwari,693,BE in Computer Engineering,kriti,f,2024

In [53]:
df.to_csv('./complete_categorization.csv', index = False)