In [2]:
import pandas as pd
import tabula as tb

In [121]:
# path_2022 = '/home/atrocity101/Desktop/repos/pandas/kucbt_eda/pdf/KUCBT_Final_Score_20221669868171.pdf'
# path_2023 = '/home/atrocity101/Desktop/repos/pandas/kucbt_eda/pdf/CBT_Score_with_Prog_2023_09_15_Print1694768486.pdf'
# path_2024 = '/home/atrocity101/Desktop/repos/pandas/kucbt_eda/pdf/CBT_Pass_List_2024_1_sept1725180337.pdf'
# path_2025 = '/home/atrocity101/Desktop/repos/pandas/kucbt_eda/pdf/KUCAT_CBT_2025_Rank_List.pdf'

In [122]:
# dfs_2022 = tb.read_pdf(path_2022, pages = 'all', stream=True, pandas_options = {'header':None})
# dfs_2023 = tb.read_pdf(path_2023, pages = 'all', lattice = True)
# dfs_2024 = tb.read_pdf(path_2024, pages = 'all', lattice = True)
# dfs_2025 = tb.read_pdf(path_2025, pages = 'all', lattice = True)

In [123]:
dfs_2025[0].head()

,KUCBT No.,Name,Applied Program,Rank
0,KUCBT_2025_1,Nabin Khadka,BSc in Bioinformatics,1952
1,KUCBT_2025_2,Sudishna Paudyal,Bachelor in Data Science,2298
2,KUCBT_2025_3,Sakar Dahal,BE in Civil Engineering (Specialization in Hyd...,3080
3,KUCBT_2025_4,Roshni Shah,BE in Computer Engineering,664
4,KUCBT_2025_5,Asmita Basnet,BArch in Architecture,1276

In [ ]:
#Discarding 2025 as it doesn't have score

In [64]:
for i,d in enumerate(dfs_2024):
    print(f"Page{i+1}: ${d.shape} and columns -> {list(d.columns)}")

Page1: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page2: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page3: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page4: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page5: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page6: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page7: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page8: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page9: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page10: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page11: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page12: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page13: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page14: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page15: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page16: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page17: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page18: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page19: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page20: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page21: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page22: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page23: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page24: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page25: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page26: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page27: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page28: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page29: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page30: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page31: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page32: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page33: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page34: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page35: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page36: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page37: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page38: $(46, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']
Page39: $(37, 4) and columns -> ['KUCBT No.', 'Name', 'CBT Score', 'Apply Program']

In [100]:
full_df = pd.concat(dfs_2024, ignore_index = True)

In [101]:
full_df.columns

Index(['KUCBT No.', 'Name', 'CBT Score', 'Apply Program'], dtype='object')

In [102]:
full_df.head()

,KUCBT No.,Name,CBT Score,Apply Program
0,KUSoE_2024_1,Aashutosh Singh,721.0,BE in Computer Engineering
1,KUSoE_2024_2,PRANAY MALLIK,641.0,BE in Computer Engineering
2,KUSoE_2024_3,SARJU SAHANI,709.0,BArch in Architecture
3,KUSoE_2024_6,Ashmit Shah,721.0,BE in Electrical & Electronic Engineering (Com...
4,KUSoE_2024_7,Surasa Silpakar,873.0,BE in Computer Engineering

In [103]:
full_df.columns = ['id', 'Name', 'KUCBT Score', 'Program']

In [104]:
full_df.head()

,id,Name,KUCBT Score,Program
0,KUSoE_2024_1,Aashutosh Singh,721.0,BE in Computer Engineering
1,KUSoE_2024_2,PRANAY MALLIK,641.0,BE in Computer Engineering
2,KUSoE_2024_3,SARJU SAHANI,709.0,BArch in Architecture
3,KUSoE_2024_6,Ashmit Shah,721.0,BE in Electrical & Electronic Engineering (Com...
4,KUSoE_2024_7,Surasa Silpakar,873.0,BE in Computer Engineering

In [105]:
full_df.isna().sum()

id             0
Name           1
KUCBT Score    1
Program        1
dtype: int64

In [106]:
full_df[full_df['Name'].isna()]

,id,Name,KUCBT Score,Program
1784,*Withheld candidates should contact with origi...,NaN,NaN,NaN

In [107]:
full_df = full_df.drop(index = 1784).copy()

In [108]:
full_df.isna().sum()

id             0
Name           0
KUCBT Score    0
Program        0
dtype: int64

In [109]:
full_df.columns

Index(['id', 'Name', 'KUCBT Score', 'Program'], dtype='object')

In [110]:
full_df.dtypes

id              object
Name            object
KUCBT Score    float64
Program         object
dtype: object

In [111]:
full_df['KUCBT Score'].dtype

dtype('float64')

In [114]:
mask = full_df['KUCBT Score'].astype(str).str.contains('*', regex = False)
full_df[mask]

Empty DataFrame
Columns: [id, Name, KUCBT Score, Program]
Index: []

In [115]:
full_df['KUCBT Score'] = full_df['KUCBT Score'].astype(str).str.replace('*', '', regex=False).str.strip()

In [116]:
full_df['KUCBT Score'] = pd.to_numeric(full_df['KUCBT Score'], errors = 'coerce').astype('Int64')

In [117]:
full_df.dtypes

id             object
Name           object
KUCBT Score     Int64
Program        object
dtype: object

In [118]:
full_df.to_csv("./csv/2024_final.csv", index = False)